apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-fdk-rss-atom-feed.yaml
- service-fdk-rss-atom-feed.yaml

images:
- name: fdk-rss-atom-feed
  newName: ghcr.io/informasjonsforvaltning/fdk-rss-atom-feed
  newTag: $(GIT_COMMIT_SHA)
