---
apiVersion: v1
kind: Service
metadata:
  name: fdk-rss-atom-feed
spec:
  selector:
    app: fdk-rss-atom-feed
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
