name: Deploy to production & demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-fdk-rss-atom-feed:
    name: Build when pull request is merged to main
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push-nox.yaml@main
    with:
      app_name: fdk-rss-atom-feed
      python_version: "3.12"
      python_architecture: x64
      environment: prod
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    name: Deploy to prod environment
    needs: [build-fdk-rss-atom-feed]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: fdk-rss-atom-feed
      environment: prod
      cluster: digdir-fdk-prod
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy-demo:
    name: Deploy to demo environment
    needs: [deploy-prod]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: fdk-rss-atom-feed
      environment: demo
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
